---
name: Upload release to Galaxy

on:
  release:
    types: [created]

jobs:
  call-workflow-sanity:
    uses: ./.github/workflows/sanity.yml

  deploy:
    runs-on: ubuntu-latest
    needs: call-workflow-sanity
    defaults:
      run:
        working-directory: ansible_collections/vultr/cloud
    steps:
      - uses: actions/checkout@v4
        with:
          path: ansible_collections/vultr/cloud

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Build and publish
        env:
          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
        run: |
          ansible-galaxy collection build .
          ansible-galaxy collection publish *.tar.gz --api-key $ANSIBLE_GALAXY_API_KEY
